# Generated by Django 4.2.11 on 2024-06-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('ethnicity', models.IntegerField(choices=[(0, 'Caucasian'), (1, 'African-American'), (2, 'Asian'), (3, 'Other')])),
                ('parental_education', models.IntegerField(choices=[(0, 'None'), (1, 'High School'), (2, 'Some College'), (3, 'Bachelor'), (4, 'Higher')])),
                ('study_time_weekly', models.FloatField()),
                ('absences', models.IntegerField()),
                ('tutoring', models.BooleanField()),
                ('parental_support', models.IntegerField()),
                ('extracurricular', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('music', models.BooleanField()),
                ('volunteering', models.BooleanField()),
                ('gpa', models.FloatField()),
                ('grade_class', models.FloatField()),
            ],
        ),
    ]
